### ISSUE TITLE
Tile rendering

### ISSUE THREAD

**Issue by sarkadicsa** [sarkadicsa/projlab#1]
Implement a proper interface in the Tile class to enable different subclasses of Tile to be rendered.

**Comment by sarkadicsa** [comment]
Visual assets support added. As of now, only assets the same size as the tiles are tested, others will probably fail.

**Comment by sarkadicsa** [comment]
Tile rendering, along with a renderer that only draws changed tiles is now working. Transparency support needs more changes in asset handling (it would need the ability to return more than one asset for a tile, and have the renderer draw them in order). Also, clearing tiles result in visual glitches - double buffering might solve the problem.

**Comment by thereallacas** [comment]
Nem kell transparency sztem
sarkadicsa <notifications@github.com> (időpont: 2016. febr. 27., Szo,
18:25) ezt írta:

**Comment by thereallacas** [comment]
Pardon, we dont need transparency
Arnócz László <lacas.shark@gmail.com> (időpont: 2016. febr. 27., Szo,
20:03) ezt írta:

**Comment by sarkadicsa** [comment]
In this case, I hereby declare this issue to be resolved.
