### ISSUE TITLE
Dropping items into a pit should destroy them

### ISSUE THREAD

**Issue by sarkadicsa** [sarkadicsa/projlab#5]
"Ha egy tárgy szakadékba esik, akkor megsemmisül."
https://www.iit.bme.hu/~projlab/feladat.shtml

**Comment by eno3nt** [comment]
done on eno3nt/master

**Comment by sarkadicsa** [comment]
Done in bcb74608d7233947d716a60aca46df1e682094d4 as well.
We should try a merge soon, before the repos get too far from each other.
